# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af7fbfbf7b338d7a933478adca6b459c98528896a6837d25b5fb00d586253cbdfee4e63a0ff04feb912a6de0afc3c423b3feb4bdc7e73f46cb203a8f88e9b2e

test:
  secret_key_base: a63e42b6f5ab808f744689b511882e2daf8a4890cec0b91b8d33dfc85781b25c76e3f5d9bb86c618cc2e19d5fa3e1453df58d5a4e6d47e51d033a174dbd333b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
